name: Build on Master

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    name: Build for Linux (i686)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install 32-bit system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib libc6-i386

      - name: Install i686 Rust host toolchain
        run: |
          rustup toolchain install stable-i686-unknown-linux-gnu --force-non-host
          rustup default stable-i686-unknown-linux-gnu

      - name: Build
        run: cargo build --release

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/release/libpawn_yaml.so dist/yaml.so

      - name: Upload Artifact to Workflow
        uses: actions/upload-artifact@v4
        with:
          name: yaml.so
          path: dist/yaml.so

  build-windows:
    name: Build for Windows (i686)
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust 32-bit toolchain
        shell: bash
        run: |
          rustup toolchain install stable-i686-pc-windows-msvc --force-non-host
          rustup default stable-i686-pc-windows-msvc

      - name: Build Crate
        run: cargo build --release

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p dist
          cp target/release/pawn_yaml.dll dist/yaml.dll

      - name: Upload Artifact to Workflow
        uses: actions/upload-artifact@v4
        with:
          name: yaml.dll
          path: dist/yaml.dll